# Generated by Django 3.0.3 on 2020-02-10 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('movie_id', models.CharField(max_length=50)),
                ('movie_url', models.URLField()),
                ('movie_thumbnail', models.CharField(max_length=200)),
                ('movie_duration', models.PositiveIntegerField()),
                ('movie_title', models.CharField(max_length=200)),
            ],
            bases=('core.basemodel',),
        ),
        migrations.CreateModel(
            name='PlayList',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.BaseModel')),
                ('movies', models.ManyToManyField(to='core.Movie')),
            ],
            bases=('core.basemodel',),
        ),
    ]
